In [1]:
import pandas as pd

In [13]:
# 1. 경찰청 지역, 시간, 요일 데이터 부르기

df_region = pd.read_csv("../data/police_region_fix.csv", encoding="utf-8-sig")
df_time = pd.read_csv("../data/police_time_fix.csv", encoding="utf-8-sig")
df_week = pd.read_csv("../data/police_week_fix.csv", encoding="utf-8-sig")

In [3]:
df_region['범죄중분류'].unique()

array(['살인기수', '살인미수등', '강도', '강간', '절도', '상해', '폭행', '협박', '마약'],
      dtype=object)

In [4]:
df_time['범죄중분류'].unique()

array(['살인기수', '살인미수등', '강도', '강간', '절도', '상해', '폭행', '협박', '마약'],
      dtype=object)

In [5]:
df_week['범죄중분류'].unique()

array(['강간', '강도', '살인기수', '살인미수등', '마약', '절도', '상해', '폭행', '협박'],
      dtype=object)

In [11]:
# 범죄중분류가 강제추행인 데이터를 요일별로 시각화 - 정렬: 요일, 시각화: 시계열 사용툴: plotly express
import plotly.express as px
# 강제추행 데이터 필터링
df_chujang = df_week[df_week['범죄중분류'] == '절도']
# 요일 순서 정의
weekday_order = ['월', '화', '수', '목', '금', '토', '일']

# 요일별 발생건수 합계 계산
chujang_weekly = df_chujang.groupby(['요일'])['발생건수'].sum().reindex(weekday_order).reset_index()
# 시계열 그래프 그리기
fig = px.line(chujang_weekly, x='요일', y='발생건수', title='요일별 절도 발생건수')
fig.show()

In [14]:
df_time

   범죄대분류  범죄중분류            시간대      범죄건수
0   강력범죄   살인기수   0시00분-02시59분     21.25
1   강력범죄  살인미수등   0시00분-02시59분     42.00
2   강력범죄     강도   0시00분-02시59분    121.38
3   강력범죄     강간   0시00분-02시59분    793.12
4   절도범죄     절도   0시00분-02시59분  15786.75
..   ...    ...            ...       ...
67  절도범죄     절도  21시00분-23시59분  23266.75
68  폭력범죄     상해  21시00분-23시59분   8100.88
69  폭력범죄     폭행  21시00분-23시59분  36436.75
70  폭력범죄     협박  21시00분-23시59분   3857.50
71  마약범죄     마약  21시00분-23시59분   1134.12

[72 rows x 4 columns]

In [15]:
daytime_total = df_time[df_time['시간대'].str.contains('09시|12시|15시')]['범죄건수'].sum()

In [18]:
df_region['지역'].unique()

array(['서울 종로구', '서울 중구', '서울 용산구', '서울 성동구', '서울 광진구', '서울 동대문구',
       '서울 중랑구', '서울 성북구', '서울 강북구', '서울 도봉구', '서울 노원구', '서울 은평구',
       '서울 서대문구', '서울 마포구', '서울 양천구', '서울 강서구', '서울 구로구', '서울 금천구',
       '서울 영등포구', '서울 동작구', '서울 관악구', '서울 서초구', '서울 강남구', '서울 송파구',
       '서울 강동구', '경기도 과천시'], dtype=object)

In [19]:
df_region.head()

  범죄대분류  범죄중분류      지역  범죄건수
0  강력범죄   살인기수  서울 종로구     0
1  강력범죄  살인미수등  서울 종로구     1
2  강력범죄     강도  서울 종로구     5
3  강력범죄     강간  서울 종로구    31
4  절도범죄     절도  서울 종로구  1180

In [ ]:
# 구를 입력했을 때 어떤 통계?